---
version: 3

images:
  base_image:
    # name: debian:latest
    name: quay.io/fedora/fedora:latest

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

# additional_build_steps:
#   prepend_final:
#     - RUN whoami
#     - RUN cat /etc/os-release
  # append_final:
  #   - RUN apt-get update && apt-get install -y python3.10 python3.10-dev sshpass git-lfs && apt-get clean && rm -rf /var/lib/apt/lists/*
  #   - RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
  #   - COPY --from=quay.io/project-receptor/receptor:1.0.0 /usr/bin/receptor /usr/bin/receptor
#     - RUN mkdir -p /var/run/receptor
#     - ADD run.sh /run.sh
#     - CMD ["/run.sh"]
#     - USER 1000
#     - RUN git lfs install
