---
collections:
  - ansible.netcommon
  - ansible.network
  - community.general
  - ansible.posix
  - networktocode.nautobot
  - community.routeros
  - cisco.asa
  - cisco.ios
  - cisco.iosxr
  - cisco.nxos
  - junipernetworks.junos
  - arista.eos
  - paloaltonetworks.panos


